version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install >> extras.sh && . ./extras.sh
#       - python3 -m pip install --upgrade pip
#       - pip3 install -r requirements.txt
#       - $CODEBUILD_GIT_MESSAGE
      - ECR_REG=236894022199.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}') 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
#       - docker build -t $REPOSITORY_URI:latest .
#       - docker build -f ./test/Dockerfile -t $APP_NAME:latest .
      - docker-compose up
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_REG/hello:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
