apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.pvname1 }}
spec:
  accessModes:
    - {{ .Values.pv.accessmodes }}
  storageClassName: {{ .Values.pv.storageclassname }}
  capacity:
    storage: {{ .Values.pv.capacity }}
  hostPath:
    path: {{ .Values.pv.hostpath1 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.pvname2 }}
spec:
  accessModes:
    - {{ .Values.pv.accessmodes }}
  storageClassName: {{ .Values.pv.storageclassname }}
  capacity:
    storage: {{ .Values.pv.capacity }}
  hostPath:
    path: {{ .Values.pv.hostpath2 }}